'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {base,categories,coverOf,emojiOf,kindOf,ownArt,slug,usesWord,type Card,type Word,type Work} from '../lib/words';
import {parseCsv,rowsToEntries,toCsv} from '../lib/csv';
import {fold} from '../lib/game';
import {readSession,writeSession} from './dict-ui';
import {WorkOptions} from './suggest-form';
type AdminWord=Word&{active:number;status:string};
type Fields={word:string;work:string;oldMeaning:string;meaning:string;example:string;addedBy:string;category:string;syllables:string;emoji:string;quote:string;note:string;scene:string};
type Filters={q:string;work:string;status:string;image:string};
type ImportResult={row:number;ok:boolean;word?:string;error?:string};
const emptyForm:Fields={word:'',work:'',oldMeaning:'',meaning:'',example:'',addedBy:'',category:categories[0],syllables:'',emoji:'',quote:'',note:'',scene:''};
const noFilter:Filters={q:'',work:'',status:'',image:''};
const fieldsOf=(w:AdminWord):Fields=>({...emptyForm,...Object.fromEntries(Object.keys(emptyForm).map(k=>[k,String((w as Record<string,unknown>)[k]??'')]))});
const statusName:Record<string,string>={approved:'Onaylı',pending:'Onay bekliyor',rejected:'Reddedildi'};
const tokenKey='gt-gorevli-oturumu';
function download(name:string,data:BlobPart,type='text/csv;charset=utf-8'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
// Terim formu: öneriyi/terimi düzenlerken ve görevli yeni terim eklerken ortak kullanılır.
// Kaydetme hatası butonun hemen üstünde gösterilir; form uzun olduğundan sayfa başındaki hata görünmez kalıyordu.
function WordForm({initial,works,busy,submit,extra,error,children}:{initial:Fields;works:Work[];busy:boolean;submit:(f:Fields)=>void;extra?:boolean;error?:string;children?:React.ReactNode}){
const [f,setF]=useState(initial);const set=(k:keyof Fields)=>(e:{target:{value:string}})=>setF({...f,[k]:e.target.value});const l=kindOf(works.find(k=>k.id===f.work));
const exampleOk=!f.word.trim()||!f.example.trim()||usesWord(f.example,f.word.trim());
return <form className="admin-form" onSubmit={e=>{e.preventDefault();submit(f);}}>
<div className="form-row"><label>{l.word} *<input required maxLength={80} placeholder={l.wordHint} value={f.word} onChange={set('word')}/></label><label>Çalışma grubu *<select required value={f.work} onChange={set('work')}><option value="">Grup seçin…</option><WorkOptions works={works}/>{extra&&<option value="__new">+ Yeni çalışma grubu ekle…</option>}</select></label></div>
<div className="form-row"><label>Karşılığı<input maxLength={60} placeholder="Örn. Gölgelendirici" value={f.syllables} onChange={set('syllables')}/></label></div>
<label>{l.old} *<textarea required rows={2} maxLength={300} placeholder={l.oldHint} value={f.oldMeaning} onChange={set('oldMeaning')}/></label>
<label>{l.now} <small>(boşsa kısa tanım kullanılır)</small><textarea rows={3} maxLength={300} value={f.meaning} onChange={set('meaning')}/></label>
<label>Örnek cümle * <small>(terimi içermeli)</small><textarea required rows={2} minLength={10} maxLength={240} value={f.example} onChange={set('example')}/>{!exampleOk&&<small className="field-error">Cümlede “{f.word.trim()}” geçmiyor.</small>}</label>
<label>Ekleyen<input maxLength={120}value={f.addedBy} onChange={set('addedBy')}/></label>
<details><summary>Ek alanlar (terim kartı için)</summary><div className="form-row"><label>Simge<input maxLength={4} placeholder="✦" value={f.emoji} onChange={set('emoji')}/></label></div>
<label>Ek not <small>(kartta tanımın altında görünür)</small><textarea rows={2} maxLength={400} value={f.note} onChange={set('note')}/></label><label>Sahne fikri <small>(görsel üretimi için)</small><textarea rows={2} maxLength={400} value={f.scene} onChange={set('scene')}/></label></details>
{children}{error&&<p className="error" role="alert">{error}</p>}<div className="button-row start"><button className="primary" disabled={busy}>{busy?'Kaydediliyor…':'Kaydet'}</button></div></form>;}
type NewWorkFields={title:string;author:string};
const noWork:NewWorkFields={title:'',author:''};
function NewWork({value,onChange}:{value:NewWorkFields;onChange:(v:NewWorkFields)=>void}){
return <details className="admin-new-work"><summary>Grup listede yoksa: yeni çalışma grubu bilgileri (grup alanında “+ Yeni çalışma grubu ekle…” seçin)</summary><div className="form-row"><label>Grup adı<input maxLength={80} value={value.title} onChange={e=>onChange({...value,title:e.target.value})}/></label><label>Kısa tanıtım<input maxLength={120} placeholder="Örn. Uydu ve roket teknolojileri" value={value.author} onChange={e=>onChange({...value,author:e.target.value})}/></label></div></details>;}
// Öğrencinin önerdiği görsel herkese açık değildir; görevli anahtarıyla indirilip gösterilir. Tıklayınca büyür.
function ProposalImage({id,version,token}:{id:string;version:number;token:string}){const [url,setUrl]=useState(''),[big,setBig]=useState(false);
useEffect(()=>{let u='',off=false;fetch(`${base}/api/admin/words?proposal=${encodeURIComponent(id)}&v=${version}`,{headers:{Authorization:`Bearer ${token}`}}).then(r=>r.ok?r.blob():null).then(b=>{if(b&&!off){u=URL.createObjectURL(b);setUrl(u);}}).catch(()=>{});return ()=>{off=true;if(u)URL.revokeObjectURL(u);};},[id,version,token]);
return <button type="button" className={`admin-proposal${big?' big':''}`} onClick={()=>setBig(!big)} aria-label={big?'Önerilen görseli küçült':'Önerilen görseli büyüt'}>{url?<img src={url} alt="Öğrencinin önerdiği görsel"/>:<i>Yükleniyor…</i>}<span>Önerilen görsel</span></button>;}
// Görevli paneli (/admin): özet, öneriler, terimler, görseller, çalışma grupları, terim kartları, Excel ve yeni terim.
export default function AdminApp(){
const [token,setToken]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[logged,setLogged]=useState(false),[view,setView]=useState('summary'),[busy,setBusy]=useState(''),[error,setError]=useState(''),[errorAt,setErrorAt]=useState(''),[notice,setNotice]=useState('');
const [pending,setPending]=useState<Card[]>([]),[cardCount,setCardCount]=useState<Record<string,number>>({}),[words,setWords]=useState<AdminWord[]>([]),[works,setWorks]=useState<Work[]>([]),[ill,setIll]=useState<Record<string,number>>({}),[prop,setProp]=useState<Record<string,number>>({}),[cov,setCov]=useState<Record<string,number>>({}),[ai,setAi]=useState(false);
const [filters,setFilters]=useState<Filters>(noFilter),[selected,setSelected]=useState<Set<string>>(new Set()),[editing,setEditing]=useState(''),[confirm,setConfirm]=useState(''),[allImages,setAllImages]=useState(false);
const [newWork,setNewWork]=useState<NewWorkFields>(noWork),[formKey,setFormKey]=useState(0),[workForm,setWorkForm]=useState<NewWorkFields>(noWork),[workEdit,setWorkEdit]=useState<NewWorkFields&{id:string}|null>(null);
const [importText,setImportText]=useState(''),[importPending,setImportPending]=useState(false),[results,setResults]=useState<ImportResult[]>([]);
async function api(url:string,init:RequestInit={},t=token){const r=await fetch(base+url,{...init,headers:{...init.headers,Authorization:`Bearer ${t}`}});const d=r.status===204?{}:await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'İşlem tamamlanamadı.');return d;}
const post=(body:object,url='/api/admin/words')=>api(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
async function load(t=token){const [c,d]=await Promise.all([api('/api/admin',{},t),api('/api/admin/words',{},t)]);setPending(c.cards);setCardCount(c.counts??{});setWords(d.words);setWorks(d.works);setIll(d.illustrated);setProp(d.proposals??{});setCov(d.covers);setAi(d.ai);}
async function run(label:string,job:()=>Promise<void>){setBusy(label);setError('');setNotice('');try{await job();}catch(e){setErrorAt(label);setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy('');}}
// Oturum yalnızca bu sekmede hatırlanır; sekme kapanınca yeniden giriş istenir.
useEffect(()=>{const t=readSession<string>(tokenKey,'');if(t)Promise.resolve(t).then(load).then(()=>{setToken(t);setLogged(true);}).catch(()=>writeSession(tokenKey,''));},[]);// eslint-disable-line react-hooks/exhaustive-deps
const login=()=>run('login',async()=>{const r=await fetch(base+'/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Giriş yapılamadı.');await load(d.token);writeSession(tokenKey,d.token);setToken(d.token);setPassword('');setLogged(true);});
const logout=()=>{writeSession(tokenKey,'');setToken('');setPassword('');setLogged(false);};
const done=async(message:string)=>{await load();setSelected(new Set());setConfirm('');setNotice(message);};
const go=(v:string,f:Partial<Filters>={})=>{setView(v);setFilters({...noFilter,...f});setSelected(new Set());setEditing('');setConfirm('');setError('');setNotice('');setResults([]);scrollTo({top:0});};
const names=(ids:string[])=>ids.map(id=>words.find(w=>w.id===id)?.word??id).join(', ');
const setStatus=(ids:string[],status:string)=>run('bulk',async()=>{const d=await post({action:'status',ids,status});await done(`${d.changed} terim → ${statusName[status].toLocaleLowerCase('tr')}.`);});
const toggle=(ids:string[],active:boolean)=>run('bulk',async()=>{for(let i=0;i<ids.length;i+=500)await post({action:'toggle',ids:ids.slice(i,i+500),active});await done(active?`${ids.length} terim yeniden görünür.`:`${ids.length} terim arşive alındı (Arşiv sekmesinde).`);});
const remove=(ids:string[])=>run('bulk',async()=>{const d=await post({action:'delete',ids});await done(`${d.deleted.length} terim silindi.`);if(d.kept.length)setError(`Terim kartı bağlı olduğu için silinmedi (gizleyebilirsiniz): ${names(d.kept)}`);});
const update=(w:AdminWord,f:Fields)=>run(w.id,async()=>{await post({action:'update',id:w.id,word:f});setEditing('');await done(`“${f.word}” güncellendi.`);});
const dropProposal=(w:AdminWord)=>run(w.id,async()=>{await post({action:'dropProposal',id:w.id});await done(`“${w.word}” için önerilen görsel reddedildi.`);});
const generate=(w:AdminWord)=>run(w.id,async()=>{await post({action:'generate',id:w.id});await done(`“${w.word}” için yeni resim üretildi.`);});
const put=(url:string,file:File)=>api(url,{method:'PUT',headers:{'Content-Type':file.type||'application/octet-stream'},body:file});
const upload=(w:AdminWord,file?:File)=>{if(file)void run(w.id,async()=>{await put(`/api/admin/words?id=${encodeURIComponent(w.id)}`,file);await done(`“${w.word}” resmi güncellendi.`);});};
// Toplu görsel: dosya adı terimle ya da kimliğiyle eşleşir ("shader.png", "guvenlik-duvari.jpg", "Güvenlik duvarı.webp").
const bulkImages=(files:File[])=>run('images',async()=>{const ok:string[]=[],skipped:string[]=[];for(const file of files){const key=slug(file.name.replace(/\.[^.]+$/,''));const w=words.find(w=>w.id===key)??words.find(w=>slug(w.word)===key);if(!w){skipped.push(file.name);continue;}try{await put(`/api/admin/words?id=${encodeURIComponent(w.id)}`,file);ok.push(w.word);}catch(e){skipped.push(`${file.name} (${e instanceof Error?e.message:'hata'})`);}}
await done(`${ok.length} görsel yüklendi${ok.length?`: ${ok.join(', ')}`:''}.`);if(skipped.length)setError(`Eşleşmeyen / yüklenemeyen: ${skipped.join(', ')}`);});
const uploadCover=(k:Work,file?:File)=>{if(file)void run(k.id,async()=>{await put(`/api/admin/works?id=${encodeURIComponent(k.id)}`,file);await done(`“${k.title}” kapağı güncellendi.`);});};
const addWork=()=>run('work',async()=>{await post({action:'create',...workForm},'/api/admin/works');setWorkForm(noWork);await done(`“${workForm.title.trim()}” çalışma gruplarına eklendi. Kapağını aşağıdan yükleyebilirsin.`);});
const saveWork=()=>{if(workEdit)void run(workEdit.id,async()=>{await post(workEdit,'/api/admin/works');setWorkEdit(null);await done(`“${workEdit.title.trim()}” güncellendi.`);});};
const moderate=(id:string,action:string)=>run(id,async()=>{await post({id,action},'/api/admin');await done(action==='approve'?'Kart ortak galeride yayımlandı.':'Kart yayımlanmadı.');});
const add=(f:Fields)=>run('add',async()=>{const d=await post({action:'create',word:f,newWork:f.work==='__new'?newWork:undefined});setNewWork(noWork);setFormKey(k=>k+1);await done(`“${d.word.word}” sözlüğe eklendi. Görselini “Görseller”den yükleyebilirsin.`);});
const exportXlsx=()=>run('export',async()=>{const r=await fetch(base+'/api/admin/export',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw Error('Dışa aktarılamadı.');download(`terimler-sozlugu-${new Date().toLocaleDateString('sv')}.xlsx`,await r.blob(),'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');setNotice('Excel dosyası indirildi: “Tüm terimler” sayfasında her sütunda filtre var; her çalışma grubu ayrıca kendi sayfasında.');});
const template=()=>download('terim-sablon.csv',toCsv([['Terim','Çalışma grubu','Karşılığı','Kısa tanım','Açıklama','Örnek cümle','Kategori','Ekleyen'],['Shader','Oyun Tasarımı','Gölgelendirici','Bir yüzeyin ekranda nasıl görüneceğini hesaplayan program','Işık, renk, parlaklık ve saydamlığı belirler; ekran kartında çalışır.','Suyun parıltısını özel bir Shader ile verdik.','Yazılım','Elif, 10-B']]));
const entries=useMemo(()=>rowsToEntries(parseCsv(importText)),[importText]);
const importRows=()=>run('import',async()=>{const d=await post({action:'import',rows:entries,pending:importPending});setResults(d.results);const ok=d.results.filter((r:ImportResult)=>r.ok).length;await load();setNotice(`${ok} / ${d.results.length} satır eklendi.`);});
// Terim formunun kendi hatası formda gösterilir, sayfa başında tekrarlanmaz.
const formError=!!error&&((view==='add'&&errorAt==='add')||(!!editing&&errorAt===editing));
const workTitle=(id:string)=>works.find(k=>k.id===id)?.title??id;
// Gizlenen (arşive alınan) terimler yalnızca Arşiv sekmesinde görünür; diğer sekmelere ve sayılara girmez.
const live=words.filter(w=>w.active),archived=words.filter(w=>!w.active);
const approved=live.filter(w=>w.status==='approved'),suggestions=live.filter(w=>w.status==='pending'),missing=approved.filter(w=>!ownArt(w,ill));
// Görünüme göre liste: öneriler, görseller (eksik), bütün terimler (filtreli).
const shown=useMemo(()=>{const q=fold(filters.q);return words.filter(w=>(view==='archive')===!w.active&&(view!=='suggest'||w.status==='pending')&&(view!=='images'||(w.status==='approved'&&(allImages||!ownArt(w,ill))))
&&(!q||fold(`${w.word} ${w.syllables} ${w.oldMeaning??''} ${w.meaning} ${w.example} ${w.addedBy??''}`).includes(q))&&(!filters.work||w.work===filters.work)&&(!filters.status||w.status===filters.status)
&&(!filters.image||(filters.image==='yes')===!!ownArt(w,ill)));},[words,view,filters,allImages,ill]);
const sel=[...selected].filter(id=>shown.some(w=>w.id===id)),allSel=shown.length>0&&sel.length===shown.length;
const pick=(id:string)=>setSelected(s=>{const n=new Set(s);if(n.has(id))n.delete(id);else n.add(id);return n;});
const bulkBar=<div className="bulk-bar" role="toolbar" aria-label="Seçili terimler"><label className="check"><input type="checkbox" checked={allSel} onChange={()=>setSelected(allSel?new Set():new Set(shown.map(w=>w.id)))}/> {sel.length?`${sel.length} seçili`:'Tümünü seç'}</label>
{!!sel.length&&(confirm==='bulk'?<><b>{sel.length} terim kalıcı olarak silinsin mi?</b><button className="primary danger" disabled={!!busy} onClick={()=>remove(sel)}>Evet, sil</button><button className="text-button" onClick={()=>setConfirm('')}>Vazgeç</button></>
:<><button className="secondary" disabled={!!busy} onClick={()=>setStatus(sel,'approved')}>✓ Onayla</button><button className="secondary" disabled={!!busy} onClick={()=>setStatus(sel,'rejected')}>Reddet</button><button className="secondary" disabled={!!busy} onClick={()=>toggle(sel,false)}>Gizle</button><button className="secondary" disabled={!!busy} onClick={()=>toggle(sel,true)}>Göster</button><button className="text-button danger-text" disabled={!!busy} onClick={()=>setConfirm('bulk')}>Sil</button></>)}</div>;
const row=(w:AdminWord)=>{const own=ownArt(w,ill),cards=cardCount[w.id]??0,proposed=prop[w.id];return <article className={`admin-row${w.active?'':' hidden-word'}${selected.has(w.id)?' selected':''}`} key={w.id}>
<input type="checkbox" aria-label={`${w.word} seç`} checked={selected.has(w.id)} onChange={()=>pick(w.id)}/>{proposed&&!ill[w.id]?<ProposalImage id={w.id} version={proposed} token={token}/>:own?<img src={own} alt=""/>:<span className="admin-placeholder">Görsel<br/>bekleniyor</span>}
<div>{editing===w.id?<WordForm initial={fieldsOf(w)} works={works} busy={busy===w.id} submit={f=>update(w,f)} error={errorAt===w.id?error:''}><button type="button" className="text-button" onClick={()=>setEditing('')}>Vazgeç</button></WordForm>:<>
<div className="row-head"><b>{w.word}</b><span className={`badge ${w.status}`}>{statusName[w.status]}</span>{!w.active&&<span className="badge off">Gizli</span>}{cards>0&&<span className="badge">{cards} kart</span>}<small>{emojiOf(w.work)} {workTitle(w.work)}{w.syllables?` · ${w.syllables}`:''} {w.addedBy?` · ekleyen: ${w.addedBy}`:''} · <code>{w.id}</code></small></div>
<p><i>Tanım:</i> {w.oldMeaning||'—'}{w.meaning!==w.oldMeaning&&<><br/><i>Açıklama:</i> {w.meaning}</>}</p><p className="admin-example">“{w.example}”</p>
<div className="button-row admin-actions">{w.status!=='approved'&&<button className="primary" disabled={!!busy} onClick={()=>setStatus([w.id],'approved')}>{proposed&&!ill[w.id]?'✓ Görselle onayla':'✓ Onayla'}</button>}{proposed&&<button className="secondary" disabled={!!busy} onClick={()=>dropProposal(w)}>Görseli reddet</button>}{w.status==='pending'&&<button className="secondary" disabled={!!busy} onClick={()=>setStatus([w.id],'rejected')}>Reddet</button>}
<button className="secondary" disabled={!!busy} onClick={()=>{setEditing(w.id);setConfirm('');}}>Düzenle</button><label className="secondary file-button">{busy===w.id?'Yükleniyor…':own?'Resmi değiştir':'Resim yükle'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{upload(w,e.target.files?.[0]);e.target.value='';}}/></label>
{ai&&w.status==='approved'&&<button className="secondary" disabled={!!busy} onClick={()=>generate(w)}>✦ YZ ile üret</button>}<button className="text-button" disabled={!!busy} onClick={()=>toggle([w.id],!w.active)}>{w.active?'Gizle':'Göster'}</button>
{confirm===w.id?<><b className="danger-text">{cards?'Terim kartı bağlı; silinemez, gizleyin.':'Kalıcı olarak silinsin mi?'}</b>{!cards&&<button className="primary danger" disabled={!!busy} onClick={()=>remove([w.id])}>Evet, sil</button>}<button className="text-button" onClick={()=>setConfirm('')}>Vazgeç</button></>:<button className="text-button danger-text" disabled={!!busy} onClick={()=>setConfirm(w.id)}>Sil</button>}</div></>}</div></article>;};
const list=<>{bulkBar}{shown.map(row)}{!shown.length&&<p className="empty-note">Bu görünümde terim yok.</p>}</>;
const nav:[string,string,number?][]=[['summary','Özet'],['suggest','Öneriler',suggestions.length],['words','Terimler',live.length],['images','Görseller',missing.length],['works','Çalışma grupları',works.length],['cards','Terim kartları',pending.length],['io','Excel'],['archive','Arşiv',archived.length],['add','+ Terim ekle']];
if(!logged)return <main className="admin-login"><Link className="text-button" href="/">← Sözlüğe dön</Link><img className="login-logo" src={`${base}/genc.png`} alt="GençTek logosu"/><div className="eyebrow">GENÇTEK BİLİŞİM SÖZLÜĞÜ</div><h1>Görevli paneli</h1><p>Terim önerilerini onaylamak; terimleri, çalışma gruplarını, görselleri ve kapakları yönetmek için kullanıcı adın ve şifrenle giriş yap.</p>
<form onSubmit={e=>{e.preventDefault();void login();}}><label>Kullanıcı adı<input autoComplete="username" autoCapitalize="none" autoCorrect="off" spellCheck={false} autoFocus value={username} onChange={e=>setUsername(e.target.value)} required/></label><label>Şifre<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button className="primary" disabled={!!busy}>{busy?'Kontrol ediliyor…':'Giriş yap'}</button></form>{error&&<p className="error" role="alert">{error}</p>}</main>;
// Özet: çalışma grubu başına sayılar ve en çok katkı verenler.
const perWork=works.map(k=>{const ws=live.filter(w=>w.work===k.id),ok=ws.filter(w=>w.status==='approved');return {k,ok:ok.length,pending:ws.filter(w=>w.status==='pending').length,missing:ok.filter(w=>!ownArt(w,ill)).length};});
const contributors=Object.entries(live.filter(w=>w.addedBy&&w.status!=='rejected').reduce<Record<string,{all:number;ok:number}>>((m,w)=>{const c=m[w.addedBy!]??={all:0,ok:0};c.all++;if(w.status==='approved')c.ok++;return m;},{})).sort((a,b)=>b[1].all-a[1].all).slice(0,10);
return <div className="admin-app"><aside><Link className="admin-brand" href="/"><img className="admin-logo" src={`${base}/genc.png`} alt="" aria-hidden="true"/><span>GençTek <b>Terimler</b><small>Görevli paneli</small></span></Link><nav aria-label="Panel bölümleri">{nav.map(([k,t,n])=><button key={k} className={view===k?'active':''} aria-current={view===k?'page':undefined} onClick={()=>go(k)}>{t}{n!==undefined&&<span className={`count${k==='suggest'&&n?' hot':''}`}>{n}</span>}</button>)}</nav>
<div className="admin-aside-foot"><Link href="/" target="_blank">Sözlüğü aç ↗</Link><button className="text-button" onClick={logout}>Çıkış yap</button></div></aside>
<main className="admin-main">{error&&!formError&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
{view==='summary'&&<><h1>Özet</h1><div className="tiles">{([['Onaylı terim',approved.length,()=>go('words',{status:'approved'})],['Onay bekleyen öneri',suggestions.length,()=>go('suggest')],['Görseli eksik',missing.length,()=>go('images')],['Çalışma grubu',works.length,()=>go('works')],['Bekleyen terim kartı',pending.length,()=>go('cards')]] as const).map(([t,n,f])=><button key={t} className={`tile${t==='Onay bekleyen öneri'&&n?' hot':''}`} onClick={f}><b>{n}</b>{t}</button>)}</div>
<h2>Çalışma grupları</h2><div className="table-wrap"><table><thead><tr><th>Çalışma grubu</th><th>Onaylı</th><th>Bekleyen</th><th>Görseli eksik</th><th>Kapak</th></tr></thead><tbody>{perWork.map(({k,ok,pending:p,missing:m})=><tr key={k.id}><td><button className="link" onClick={()=>go('words',{work:k.id})}>{emojiOf(k.id)} {k.title}</button></td><td>{ok}</td><td>{p?<button className="link hot" onClick={()=>go('suggest',{work:k.id})}>{p}</button>:0}</td><td>{m?<button className="link" onClick={()=>go('images',{work:k.id})}>{m}</button>:'✓'}</td><td>{coverOf(k.id,cov)?'✓':<button className="link" onClick={()=>go('works')}>yok</button>}</td></tr>)}</tbody></table></div>
<h2>En çok katkı verenler</h2>{contributors.length?<ol className="contributors">{contributors.map(([name,c])=><li key={name}><button className="link" onClick={()=>go('words',{q:name})}>{name}</button><span>{c.all} öneri · {c.ok} onaylı</span></li>)}</ol>:<p className="empty-note">Henüz “ekleyen” bilgisiyle gelen öneri yok.</p>}</>}
{view==='suggest'&&<><h1>Terim önerileri</h1><p>“Terim ekle” formundan gönderilen terimler. Onaylananlar sözlüğe, çalışma grubu sayfalarına ve oyunlara girer; reddedilenler silinmez, “Terimler” bölümünden geri alınabilir. Kaydetmeden önce “Düzenle” ile tanımı ve kategoriyi düzeltebilirsin.</p><div className="filter-bar"><input type="search" placeholder="Ara: terim, tanım, ekleyen…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/><select aria-label="Çalışma grubu" value={filters.work} onChange={e=>setFilters({...filters,work:e.target.value})}><option value="">Bütün çalışma grupları</option>{works.map(k=><option key={k.id} value={k.id}>{emojiOf(k.id)} {k.title}</option>)}</select></div>{list}</>}
{view==='words'&&<><h1>Terimler</h1><div className="filter-bar"><input type="search" placeholder="Ara: terim, karşılık, tanım, cümle, ekleyen…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/>
<select aria-label="Çalışma grubu" value={filters.work} onChange={e=>setFilters({...filters,work:e.target.value})}><option value="">Bütün çalışma grupları</option>{works.map(k=><option key={k.id} value={k.id}>{emojiOf(k.id)} {k.title}</option>)}</select>
<select aria-label="Durum" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">Bütün durumlar</option>{Object.entries(statusName).map(([k,t])=><option key={k} value={k}>{t}</option>)}</select>
<select aria-label="Görsel" value={filters.image} onChange={e=>setFilters({...filters,image:e.target.value})}><option value="">Görsel: hepsi</option><option value="yes">Görseli var</option><option value="no">Görseli yok</option></select>
{JSON.stringify(filters)!==JSON.stringify(noFilter)&&<button className="text-button" onClick={()=>setFilters(noFilter)}>Filtreleri temizle</button>}</div><p className="result-count">{shown.length} terim</p>{list}</>}
{view==='images'&&<><h1>Görseller</h1><p>Görseli olmayan terimler sözlükte “Görsel bekleniyor” olarak görünür. Dosyaları toplu seçebilirsin; dosya adı terimle ya da kimliğiyle eşleşir (<code>shader.png</code>, <code>guvenlik-duvari.jpg</code>). Kare (1:1) PNG, JPG veya WEBP, en fazla 8 MB.</p>
<div className="button-row start"><label className="primary file-button">{busy==='images'?'Yükleniyor…':'⇪ Toplu görsel yükle'}<input type="file" multiple accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{const files=[...e.target.files??[]];e.target.value='';if(files.length)bulkImages(files);}}/></label><label className="check"><input type="checkbox" checked={allImages} onChange={e=>setAllImages(e.target.checked)}/> Görseli olanları da göster</label></div>{!shown.length&&!allImages?<p className="empty-note">Bütün onaylı terimlerin görseli var. 🎉</p>:list}</>}
{view==='works'&&<><h1>Çalışma grupları</h1><p>Gruplar sözlükte “Çalışma Grupları” sayfasında, sözlüğün bölümleri olarak ve oyun filtrelerinde görünür. Kapak yüklenmemişse grubun simgesi gösterilir.</p><form className="admin-form" onSubmit={e=>{e.preventDefault();void addWork();}}><h2>Yeni çalışma grubu ekle</h2><div className="form-row"><label>Grup adı<input required minLength={2} maxLength={80} value={workForm.title} onChange={e=>setWorkForm({...workForm,title:e.target.value})}/></label><label>Kısa tanıtım<input required minLength={2} maxLength={120} placeholder="Örn. Uydu ve roket teknolojileri" value={workForm.author} onChange={e=>setWorkForm({...workForm,author:e.target.value})}/></label></div><button className="primary" disabled={!!busy}>{busy==='work'?'Ekleniyor…':'Grubu ekle'}</button></form><h2>Kayıtlı gruplar</h2>{works.map(k=><article className="admin-row" key={k.id}>{coverOf(k.id,cov)?<img src={coverOf(k.id,cov)!} alt=""/>:<span className="admin-placeholder group-placeholder">{emojiOf(k.id)}</span>}<div>{workEdit?.id===k.id?<form className="admin-form" onSubmit={e=>{e.preventDefault();saveWork();}}><div className="form-row"><label>Grup adı<input required minLength={2} maxLength={80} value={workEdit.title} onChange={e=>setWorkEdit({...workEdit,title:e.target.value})}/></label><label>Kısa tanıtım<input required minLength={2} maxLength={120} value={workEdit.author} onChange={e=>setWorkEdit({...workEdit,author:e.target.value})}/></label></div><div className="button-row start"><button className="primary" disabled={!!busy}>Kaydet</button><button type="button" className="text-button" onClick={()=>setWorkEdit(null)}>Vazgeç</button></div></form>:<><div className="row-head"><b>{emojiOf(k.id)} {k.title}</b><small>{k.author} · {approved.filter(w=>w.work===k.id).length} onaylı terim</small></div><div className="button-row admin-actions"><label className="secondary file-button">{cov[k.id]?'Kapağı değiştir':'Kapak yükle'}<input type="file" accept="image/png,image/jpeg,image/webp" disabled={!!busy} onChange={e=>{uploadCover(k,e.target.files?.[0]);e.target.value='';}}/></label><button className="secondary" disabled={!!busy} onClick={()=>setWorkEdit({id:k.id,title:k.title,author:k.author})}>Düzenle</button><button className="text-button" onClick={()=>go('words',{work:k.id})}>Terimlerini gör →</button></div></>}</div></article>)}</>}
{view==='cards'&&<><h1>Terim kartları</h1><p>Katılımcıların “Kart yap” bölümünde oluşturduğu kartlar. Yayımlananlar “Ortak kartlar” sayfasında görünür.</p>{!pending.length&&<p className="empty-note">Onay bekleyen terim kartı yok.</p>}{pending.map(c=><article className="admin-row" key={c.id}><img src={c.image} alt="İncelenecek kart görseli"/><div><div className="row-head"><b>{words.find(w=>w.id===c.wordId)?.word??c.wordId}</b><small>{c.nickname} · {new Date(c.createdAt).toLocaleString('tr-TR')}</small></div><p>{c.sentence}</p><small>Görsel tarifi: {c.scene}</small><div className="button-row admin-actions"><button className="primary" disabled={!!busy} onClick={()=>moderate(c.id,'approve')}>Yayımla</button><button className="text-button" disabled={!!busy} onClick={()=>moderate(c.id,'reject')}>Yayımlama</button></div></div></article>)}</>}
{view==='archive'&&<><h1>Arşiv</h1><p>Gizlenen terimler burada durur; sözlükte, oyunlarda ve Excel dosyasında görünmez. Geri almak için terimi seçip “Göster”e bas.</p><div className="filter-bar"><input type="search" placeholder="Arşivde ara…" value={filters.q} onChange={e=>setFilters({...filters,q:e.target.value})}/></div><p className="result-count">{shown.length} terim</p>{list}</>}
{view==='io'&&<><h1>Excel</h1><section className="io-box"><h2>Dışa aktar</h2><p>Sözlükte yayında olan terimler (onaylılar; öneriler ve arşivdekiler hariç) Excel dosyası (.xlsx) olarak iner:</p><ul className="io-list"><li><b>Tüm terimler</b> sayfası: her sütunda Excel filtresi var; çalışma grubuna, kategoriye, görsele ya da ekleyene göre süzebilirsin.</li><li><b>Özet</b> sayfası: grup başına terim ve görseli eksik terim sayıları.</li><li>Her çalışma grubu için <b>ayrı bir sayfa</b>, o da filtreli.</li></ul><button className="primary" disabled={!!busy} onClick={exportXlsx}>{busy==='export'?'Hazırlanıyor…':'↓ Excel dosyasını indir (.xlsx)'}</button></section>
<section className="io-box"><h2>İçe aktar</h2><p>Excel’de şu sütunlarla bir tablo hazırla: <b>Terim · Çalışma grubu · Karşılığı · Kısa tanım · Açıklama · Örnek cümle · Kategori · Ekleyen</b> (dışa aktarılan dosyanın sütunları da tanınır). Satırları başlıkla birlikte seçip kopyala ve aşağıya yapıştır ya da “CSV UTF-8” olarak kaydedip dosyayı seç. Çalışma grubu adı listedeki gruplardan biri olmalı. <button className="text-button" onClick={template}>Örnek şablonu indir</button></p>
<div className="button-row start"><label className="secondary file-button">Dosya seç (.csv)<input type="file" accept=".csv,.tsv,.txt,text/csv,text/plain" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(f){setImportText(await f.text());setResults([]);}}}/></label>{importText&&<button className="text-button" onClick={()=>{setImportText('');setResults([]);}}>Temizle</button>}</div>
<label className="sr-only" htmlFor="import-text">Yapıştırılan tablo</label><textarea id="import-text" rows={6} placeholder="Excel’den kopyaladığın satırları buraya yapıştır…" value={importText} onChange={e=>{setImportText(e.target.value);setResults([]);}}/>
{!!entries.length&&<><p className="result-count">{entries.length} satır okundu{entries.length>500?' — tek seferde en fazla 500 satır aktarılabilir':''}.</p><div className="table-wrap"><table><thead><tr><th>#</th><th>Terim</th><th>Çalışma grubu</th><th>Karşılığı</th><th>Kısa tanım</th><th>Açıklama</th><th>Örnek cümle</th><th>Kategori</th><th>Ekleyen</th>{!!results.length&&<th>Sonuç</th>}</tr></thead><tbody>{entries.slice(0,500).map((r,i)=>{const res=results.find(x=>x.row===i+1);return <tr key={i} className={res?res.ok?'ok':'bad':''}><td>{i+1}</td><td><b>{r.word}</b></td><td>{r.work}</td><td>{r.syllables}</td><td>{r.oldMeaning}</td><td>{r.meaning}</td><td>{r.example}</td><td>{r.category}</td><td>{r.addedBy}</td>{!!results.length&&<td>{res?res.ok?'✓ eklendi':res.error:''}</td>}</tr>;})}</tbody></table></div>
<div className="button-row start"><label className="check"><input type="checkbox" checked={importPending} onChange={e=>setImportPending(e.target.checked)}/> Onay bekleyen öneri olarak ekle</label><button className="primary" disabled={!!busy||entries.length>500||!!results.length} onClick={importRows}>{busy==='import'?'Aktarılıyor…':`${entries.length} satırı içe aktar`}</button></div></>}</section></>}
{view==='add'&&<><h1>Terim ekle</h1><p>Görevlinin eklediği terim doğrudan sözlüğe girer. Çok sayıda terim için “Excel” bölümünü kullan.</p><WordForm key={formKey} initial={{...emptyForm,work:works[0]?.id??''}} works={works} busy={busy==='add'} submit={add} extra error={errorAt==='add'?error:''}><NewWork value={newWork} onChange={setNewWork}/></WordForm></>}
</main></div>;}
