'use client';
import {useEffect,useRef,useState} from 'react';
import {art,base,emojiOf,wordArt,workOf,usesWord,categories as wordCategories,type Word,type Work,type Card} from '../lib/words';
import QRCode from 'qrcode';
import Link from 'next/link';
import Book from './book';
import WorksView from './works-view';
import GuessGame from './guess-game';
import SuggestForm from './suggest-form';
import {Meanings} from './dict-ui';

const categories=['Tümü',...wordCategories];
const mineKey='gt-terimler-kartlarim';
// "Sözlüğüm": öğrencinin oluşturduğu kartların kimlikleri yalnızca kendi tarayıcısında tutulur.
function readMine():string[]{try{const v=JSON.parse(localStorage.getItem(mineKey)||'[]');return Array.isArray(v)?v.filter(x=>typeof x==='string'):[];}catch{return [];}}
function saveMine(ids:string[]){try{localStorage.setItem(mineKey,JSON.stringify(ids.slice(-60)));}catch{}}
const styles=['İzometrik çizim','Çizgi roman','Fütüristik'];
function Source({w,k}:{w:Word;k:Work}){return <div className="source">{w.note&&<p>{w.note}</p>}<p className="entry-example">“{w.example}”</p><small>ÇALIŞMA GRUBU · {emojiOf(k.id)} {k.title}</small></div>;}
// Yazdırılabilir kitapçık: kapak + her kart için bir sayfa. Ekranda gizlidir, yalnızca "yazdır" sırasında görünür.
function Booklet({title,cards,words,works}:{title:string;cards:Card[];words:Word[];works:Work[]}){return <div className="booklet" aria-hidden="true"><section className="booklet-page booklet-cover"><span className="print-brand">GENÇTEK TERİMLER SÖZLÜĞÜ</span><h1>{title}</h1><p>Çalışma gruplarının terimleri, bizim cümlelerimiz.</p><small>{cards.length} terim · {new Date().toLocaleDateString('tr-TR')}</small></section>{cards.map(c=>{const w=words.find(x=>x.id===c.wordId);if(!w)return null;const k=workOf(works,w);return <section className="booklet-page" key={c.id}><img src={c.image} alt=""/><h2>{w.word}</h2><small className="card-source">{w.syllables&&w.syllables!==w.word&&`${w.syllables} · `}{k.title}</small><p>{w.meaning}</p><blockquote>“{c.sentence}”</blockquote><small>✦ {c.nickname} · {new Date(c.createdAt).toLocaleDateString('tr-TR')}</small></section>;})}</div>;}
function printBooklet(){document.body.classList.add('booklet-print');const done=()=>{document.body.classList.remove('booklet-print');window.removeEventListener('afterprint',done);};window.addEventListener('afterprint',done);window.print();}
export default function Studio({words,works,illustrated,covers}:{words:Word[];works:Work[];illustrated:Record<string,number>;covers:Record<string,number>}){
const pic=(w:Word)=>illustrated[w.id]?wordArt(w.id,illustrated[w.id]):art(w.image);
const src=(w:Word)=>workOf(works,w);
const [tab,setTab]=useState('explore'),[category,setCategory]=useState('Tümü'),[work,setWork]=useState('Tümü'),[query,setQuery]=useState('');
const [selected,setSelected]=useState<Word|null>(null),[step,setStep]=useState(1),[guess,setGuess]=useState(''),[revealed,setRevealed]=useState(false);
const [sentence,setSentence]=useState(''),[scene,setScene]=useState(''),[nickname,setNickname]=useState(''),[style,setStyle]=useState(styles[0]);
const [ai,setAi]=useState(false),[teacher,setTeacher]=useState(false),[feedback,setFeedback]=useState<{ok:boolean;text:string}|null>(null),[checking,setChecking]=useState(false),[mine,setMine]=useState<Card[]>([]),[mode,setMode]=useState('demo'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
const [card,setCard]=useState<Card|null>(null),[gallery,setGallery]=useState<Card[]>([]),[loading,setLoading]=useState(false);
const [suggestWork,setSuggestWork]=useState('');
const [qr,setQr]=useState('');
useEffect(()=>{let active=true;setQr('');if(card)QRCode.toDataURL(`${location.origin}${base}/?kart=${card.id}`,{width:180,margin:2,color:{dark:'#243130',light:'#ffffff'}}).then(url=>{if(active)setQr(url);}).catch(()=>{});return()=>{active=false;};},[card]);
const dialog=useRef<HTMLDialogElement>(null),focusReturn=useRef<HTMLElement|null>(null);
useEffect(()=>{fetch(base+'/api/config').then(r=>r.json()).then(d=>{setAi(d.ai);setTeacher(d.teacher);setMode(d.ai?'ai':'demo');}).catch(()=>{});const id=new URLSearchParams(location.search).get('kart');if(id){fetch(base+`/api/cards?id=${encodeURIComponent(id)}`).then(async r=>{const d=await r.json();if(!r.ok)throw Error('Bu kart bulunamadı.');return d;}).then(d=>{setCard(d.card);setSelected(words.find(w=>w.id===d.card.wordId)||null);setStep(4);}).catch(e=>setError(e.message));}},[]);
useEffect(()=>{if(selected){focusReturn.current=document.activeElement as HTMLElement;dialog.current?.showModal();}else if(dialog.current?.open){dialog.current.close();focusReturn.current?.focus();}},[selected]);
async function loadGallery(){setLoading(true);setError('');try{const r=await fetch(base+'/api/cards');const d=await r.json();if(!r.ok)throw Error(d.error);setGallery(d.cards);}catch(e){setError(e instanceof Error?e.message:'Sözlük yüklenemedi.');}finally{setLoading(false);}}
async function loadMine(){const ids=readMine();if(!ids.length){setMine([]);return;}setLoading(true);setError('');try{const r=await fetch(base+`/api/cards?ids=${ids.join(',')}`);const d=await r.json();if(!r.ok)throw Error(d.error);setMine(d.cards);}catch(e){setError(e instanceof Error?e.message:'Sözlüğün yüklenemedi.');}finally{setLoading(false);}}
function changeTab(next:string){setTab(next);setError('');scrollTo({top:0});if(next==='gallery')void loadGallery();if(next==='mine')void loadMine();}
async function askTeacher(){if(!selected||checking)return;setChecking(true);setFeedback(null);try{const r=await fetch(base+'/api/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wordId:selected.id,sentence})});const d=await r.json();if(!r.ok)throw Error(d.error);setFeedback({ok:d.ok,text:d.feedback});}catch(e){setFeedback({ok:false,text:e instanceof Error?e.message:'Yapay zekâ öğretmen şu anda yanıt veremiyor.'});}finally{setChecking(false);}}
function choose(word:Word){setSelected(word);setStep(1);setGuess('');setRevealed(false);setFeedback(null);setSentence('');setScene('');setNickname('');setStyle(styles[0]);setCard(null);setError('');setNotice('');}
function close(){if(busy)return;setSelected(null);setError('');setNotice('');if(location.search.includes('kart='))history.replaceState(null,'',location.pathname);}
function goCreate(){document.getElementById('words')?.scrollIntoView({behavior:'smooth'});document.getElementById('search')?.focus({preventScroll:true});}
async function create(){if(!selected||busy)return;setBusy(true);setError('');try{const r=await fetch(base+'/api/cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wordId:selected.id,sentence,scene,nickname,style,mode})});const d=await r.json();if(!r.ok)throw Error(d.error);setCard(d.card);setStep(4);saveMine([...readMine().filter(x=>x!==d.card.id),d.card.id]);}catch(e){setError(e instanceof Error?e.message:'Kart oluşturulamadı.');}finally{setBusy(false);}}
async function copy(){if(!card)return;try{await navigator.clipboard.writeText(`${location.origin}${base}/?kart=${card.id}`);setNotice('Kartının bağlantısı kopyalandı.');}catch{setNotice(`Kart bağlantın: ${location.origin}${base}/?kart=${card.id}`);}}
async function download(){if(!card||!selected)return;setError('');try{const canvas=document.createElement('canvas');canvas.width=1000;canvas.height=1700;const c=canvas.getContext('2d')!;c.fillStyle='#faf6ee';c.fillRect(0,0,1000,1700);const img=new Image();img.src=card.image;await img.decode();const scale=Math.max(880/img.width,600/img.height);c.save();c.beginPath();c.rect(60,140,880,600);c.clip();c.drawImage(img,60+(880-img.width*scale)/2,140+(600-img.height*scale)/2,img.width*scale,img.height*scale);c.restore();c.fillStyle='#de593a';c.font='bold 25px Arial';c.fillText('GENÇTEK  /  TERİMLER SÖZLÜĞÜ',60,85);c.fillStyle='#202a30';c.font='bold 78px Georgia';c.fillText(selected.word,60,845);function wrap(text:string,y:number,size:number,font='Arial'){c.font=`${size}px ${font}`;let line='';for(const word of text.split(' ')){const next=line+word+' ';if(c.measureText(next).width>870){c.fillText(line,60,y);line=word+' ';y+=size*1.45;}else line=next;}c.fillText(line,60,y);return y+size*1.45;}let y=wrap(selected.meaning,910,28);y=wrap('“'+card.sentence+'”',y+40,34,'Georgia');c.font='24px Arial';c.fillText(card.nickname,60,Math.max(1460,y+25));c.fillStyle='#6d7374';c.font='20px Arial';c.fillText(new Date(card.createdAt).toLocaleDateString('tr-TR')+'  ·  '+(card.mode==='ai'?'Yapay zekâ görseli':'Hazır görselle oluşturuldu'),60,1530);c.fillText('Çalışma grubu: '+src(selected).title+'  ·  '+card.id.slice(0,8).toUpperCase(),60,1600);if(qr){const q=new Image();q.src=qr;await q.decode();c.drawImage(q,760,1435,180,180);}const url=canvas.toDataURL('image/png');const a=document.createElement('a');a.download=`genctek-terim-${selected.id}-${card.id.slice(0,8)}.png`;a.href=url;a.click();setNotice('Terim kartın indirildi.');}catch{setError('Görsel indirilemedi. Yazdır seçeneğini kullanabilirsin.');}}
const filtered=words.filter(w=>(category==='Tümü'||w.category===category)&&(work==='Tümü'||w.work===work)&&`${w.word} ${w.syllables} ${w.oldMeaning??''} ${w.meaning} ${src(w).title}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')));
const sentenceValid=!!selected&&sentence.trim().length>=10&&usesWord(sentence,selected.word);
return <>
<header className="header"><a className="brand" href={`${base}/`} aria-label="GençTek Terimler Sözlüğü ana sayfa"><img className="brand-logo" src={`${base}/genc.png`} alt="" aria-hidden="true"/><span>GençTek<br/><b>Terimler Sözlüğü</b></span></a><nav aria-label="Ana menü">{([['explore','Ana sayfa'],['book','Sözlük'],['works','Çalışma Grupları'],['game','Oyun']] as const).map(([k,t])=><button key={k} className={tab===k||(k==='explore'&&['mine','gallery','about'].includes(tab))?'active':''} aria-current={tab===k?'page':undefined} onClick={()=>changeTab(k)}>{t}</button>)}<button className={`nav-add${tab==='add'?' active':''}`} onClick={()=>{setSuggestWork('');changeTab('add');}}>+ Terim ekle</button></nav><span className="festival">GENÇTEK <small>ÖĞREN. ÜRET. PAYLAŞ.</small></span></header>
<main>
{tab==='explore'&&<>
<section className="home-start"><span className="vitrin-logo" aria-hidden="true"><img src={`${base}/genc.png`} alt=""/></span><div className="eyebrow"><span className="live-dot"/> GENÇTEK TERİMLER SÖZLÜĞÜ · {works.length} ÇALIŞMA GRUBU · {words.length} TERİM</div><h1>Terimleri <em>keşfet.</em></h1><p>GençTek çalışma gruplarının ortak dili: her grubun temel terimleri, karşılıkları, tanımları ve örnek kullanımlarıyla. Oku, oyna, kendi kartını hazırla ya da sözlüğe yeni terim öner.</p>
<div className="activities">{([['book','📖','Sözlüğü oku','Terimleri grup grup, sayfa sayfa incele; sayfa sonunda eşleştir.'],['works','▦','Çalışma grupları','Grubunu seç, gizli terimleri tanımından tahmin ederek aç.'],['game','🎯','Oyun oyna','Terimi ya da tanımını bul; seri yap, skorunu yükselt.'],['card','✦','Kart yap','Bir terim seç, kendi cümlenle görselli terim kartını oluştur.'],['add','✎','Terim ekle','Sözlükte olmayan bir terimi görevli onayına gönder.'],['gallery','◎','Ortak kartlar','Diğer katılımcıların hazırladığı terim kartlarına göz at.']] as const).map(([k,i,t,d])=><button key={k} className="activity" onClick={()=>{if(k==='card'){goCreate();return;}setSuggestWork('');changeTab(k);}}><span aria-hidden="true">{i}</span><b>{t}</b><small>{d}</small><em>↗</em></button>)}</div></section>
<section id="words" className="words-section"><div className="section-heading"><div><div className="eyebrow">KART YAP</div><h2>Bir terim <em>seç</em></h2><p>Terime dokun; tanımını öğren, cümleni yaz, kartını al. Kategoriye, çalışma grubuna göre süz ya da ara.</p></div><span className="count">{filtered.length} / {words.length} terim</span><button className="text-button" onClick={()=>choose(words[Math.floor(Math.random()*words.length)])}>✧ Bana bir terim seç</button></div><div className="filters"><div className="chips" aria-label="Terim kategorileri">{categories.map(c=><button key={c} className={category===c?'chosen':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="filter-tools"><label className="search"><span>❧</span><select value={work} onChange={e=>setWork(e.target.value)} aria-label="Çalışma grubuna göre süz"><option value="Tümü">Tüm çalışma grupları</option>{works.filter(k=>words.some(w=>w.work===k.id)).map(k=><option key={k.id} value={k.id}>{emojiOf(k.id)} {k.title}</option>)}</select></label><label className="search"><span>⌕</span><input id="search" placeholder="Terim, karşılık ya da tanım ara…" value={query} onChange={e=>setQuery(e.target.value)} aria-label="Terim ara"/></label></div></div><div className="word-grid">{filtered.map(w=><button key={w.id} className={`word-card ${w.color}`} onClick={()=>choose(w)}><div className="word-top"><span className="word-category">{w.category}</span><span className="word-number">{String(words.indexOf(w)+1).padStart(2,'0')}</span></div><div className="word-illustration"><img src={pic(w)} alt="" loading="lazy"/><span aria-hidden="true">{w.emoji}</span></div><h3>{w.word}</h3><p>{w.syllables}</p><small className="word-work">{emojiOf(w.work)} {src(w).title}</small><div className="word-bottom"><span>Bu terimi keşfet</span><span>↗</span></div></button>)}</div>{!filtered.length&&<div className="empty"><h3>Bu aramada terim bulunamadı.</h3><button className="secondary" onClick={()=>{setQuery('');setCategory('Tümü');setWork('Tümü');}}>Tüm terimleri göster</button></div>}<p className="source-note">ⓘ Terimler GençTek çalışma gruplarına göre derlendi; görevli panelinden düzenlenir ve yeni terimlerle büyür.</p></section>
<section className="community-banner"><div className="community-mark">a<span>✦</span></div><div><div className="eyebrow">BİRLİKTE YAZDIĞIMIZ BİR SÖZLÜK</div><h2>Aynı terim, farklı bakışlar.</h2><p>Diğer katılımcıların terimleri nasıl kullandığına göz at.</p></div><div className="button-row"><button className="secondary" onClick={()=>changeTab('gallery')}>Ortak kartları keşfet ↗</button><button className="text-button" onClick={()=>changeTab('mine')}>Kartlarım</button></div></section>
</>}
{tab==='book'&&<Book words={words} works={works} ill={illustrated} onAdd={()=>{setSuggestWork('');changeTab('add');}}/>}
{tab==='works'&&<WorksView words={words} works={works} ill={illustrated} covers={covers} onAdd={id=>{setSuggestWork(id);changeTab('add');}}/>}
{tab==='game'&&<GuessGame words={words} works={works} ill={illustrated}/>}
{tab==='add'&&<SuggestForm key={suggestWork} works={works} initialWork={suggestWork}/>}
{tab==='gallery'&&<section className="standalone"><div className="eyebrow">BİRLİKTE BÜYÜYEN BİR SÖZLÜK</div><h1>Ortak <em>kartlar.</em></h1><p>Her terimde başka bir bakış. Görevli onayından geçen kartlar burada buluşuyor.</p><div className="button-row start"><button className="text-button" onClick={loadGallery}>↻ Sözlüğü yenile</button>{!!gallery.length&&<button className="secondary" onClick={printBooklet}>⎙ Ortak sözlüğü yazdır / PDF</button>}</div>{loading?<p role="status">Kartlar yükleniyor…</p>:gallery.length?<div className="gallery-grid">{gallery.map(c=>{const w=words.find(w=>w.id===c.wordId);if(!w)return null;return <button className="gallery-card" key={c.id} onClick={()=>{setCard(c);setSelected(w);setStep(4);}}><img src={c.image} alt={`${w.word} teriminin görseli`}/><div><span className="eyebrow">{c.mode==='ai'?'YAPAY ZEKÂ GÖRSELİ':'HAZIR GÖRSELLİ KART'}</span><h2>{w.word}</h2><p>“{c.sentence}”</p><small>{c.nickname} ↗</small></div></button>;})}</div>:!error&&<div className="empty"><span className="empty-symbol">✧</span><h2>İlk kart seninki olsun.</h2><p>Henüz yayımlanmış kart yok. Kendi kartını oluştur ve bu sözlüğün bir parçası ol.</p><button className="primary" onClick={()=>changeTab('explore')}>Terim seç ↗</button></div>}</section>}
{tab==='mine'&&<section className="standalone"><div className="eyebrow">BU CİHAZDA OLUŞTURDUĞUN KARTLAR</div><h1>Benim <em>sözlüğüm.</em></h1><p>Oluşturduğun her kart buraya eklenir. Hepsini bir kitapçık olarak yazdırabilir ya da PDF olarak kaydedebilirsin.</p>{loading?<p role="status">Kartların yükleniyor…</p>:mine.length?<><div className="button-row start"><button className="primary" onClick={printBooklet}>⎙ Sözlüğümü yazdır / PDF</button><button className="text-button" onClick={()=>changeTab('explore')}>+ Yeni kart yap</button></div><div className="gallery-grid">{mine.map(c=>{const w=words.find(w=>w.id===c.wordId);if(!w)return null;return <button className="gallery-card" key={c.id} onClick={()=>{setCard(c);setSelected(w);setStep(4);}}><img src={c.image} alt={`${w.word} teriminin görseli`}/><div><span className="eyebrow">{c.approved===1?'ORTAK SÖZLÜKTE':c.approved===-1?'YALNIZCA SENİN SÖZLÜĞÜNDE':'ONAY BEKLİYOR'}</span><h2>{w.word}</h2><p>“{c.sentence}”</p><small>{src(w).title} ↗</small></div></button>;})}</div></>:!error&&<div className="empty"><span className="empty-symbol">✧</span><h2>Sözlüğün seni bekliyor.</h2><p>Bir terim seç, cümleni yaz ve ilk kartını oluştur. Kartların bu cihazda hatırlanır.</p><button className="primary" onClick={()=>changeTab('explore')}>Terim seç ↗</button></div>}</section>}
{tab==='about'&&<section className="standalone about"><div className="eyebrow">GENÇTEK · ÇALIŞMA GRUPLARI</div><h1>Nasıl <em>çalışır?</em></h1><p>GençTek çalışma gruplarının terimlerinden oluşan, görevli onayıyla büyüyen, oyunlaştırılmış bir terimler sözlüğü. Lise öğrencileri ve alanı öğrenen herkes için.</p>{[['01','Terimi bul, öner','Çalışma grubunda karşılaştığın ve sözlükte olmayan bir terimi “Terim ekle” formuyla karşılığı, kısa tanımı ve örnek cümlesiyle gönder.'],['02','Görevli onaylar','Görevli, önerileri panelde düzenler ve onaylar; terim görsellerini ve grup kapaklarını yükler, sözlüğü Excel olarak dışa aktarır.'],['03','Sözlük büyür, oyunla pekişir','Onaylanan terimler Sözlük’e, çalışma grubu sayfalarına ve Terimi / Tanımını Bul oyununa girer. Sayfa sonlarında eşleştirme yaparsın.'],['04','Kartını hazırla','Bir terimi kendi cümlende kullan, görselli terim kartını indir ya da yazdır; kartlarından kişisel sözlük kitapçığı oluştur.']].map(([n,t,d])=><article className="about-step" key={n}><span>{n}</span><div><h2>{t}</h2><p>{d}</p></div></article>)}<h2 className="plan-title">Çalışma grupları</h2><div className="plan-table"><table><thead><tr><th>Grup</th><th>Odak</th><th>Terim</th></tr></thead><tbody>{works.map(k=><tr key={k.id}><th>{emojiOf(k.id)} {k.title}</th><td>{k.author}</td><td><button className="link" onClick={()=>changeTab('works')}>{words.filter(w=>w.work===k.id).length} terim ↗</button></td></tr>)}</tbody></table></div>
<div className="info-box">Gerçek adını, okulunu veya iletişim bilgilerini yazmana gerek yok. Bir takma ad yeterli. Kart bağlantısını bilenler kartını görüntüleyebilir.</div><button className="primary" onClick={()=>changeTab('explore')}>Keşfetmeye başla ↗</button></section>}
{error&&!selected&&<p className="error" role="alert">{error}</p>}
</main>
<footer><a className="footer-brand" href={`${base}/`}><img className="footer-logo" src={`${base}/genc.png`} alt="" aria-hidden="true"/>GençTek Terimler Sözlüğü</a><p>Her çalışma grubunun ortak dili.</p><nav className="footer-links" aria-label="Diğer bölümler"><button className="text-button" onClick={()=>changeTab('mine')}>Kartlarım</button><button className="text-button" onClick={()=>changeTab('gallery')}>Ortak kartlar</button><button className="text-button" onClick={()=>changeTab('about')}>Nasıl çalışır?</button><Link className="text-button" href="/admin">Görevli paneli ↗</Link></nav><small>GençTek çalışma grupları için hazırlanmış terimler sözlüğü.</small></footer>
{tab==='mine'&&<Booklet title="Benim Sözlüğüm" cards={mine} words={words} works={works}/>}{tab==='gallery'&&<Booklet title="Ortak Kartlarımız" cards={[...gallery].reverse()} words={words} works={works}/>}
<dialog ref={dialog} onCancel={e=>{e.preventDefault();close();}}><div className="dialog-content"><button className="close" aria-label="Pencereyi kapat" disabled={busy} onClick={close}>×</button>
{selected&&<>
<div className="modal-progress" aria-label={`Adım ${step} / 4`}>{['Keşfet','Cümleni kur','Görselleştir','Kartını al'].map((s,i)=><span className={step>=i+1?'done':''} key={s}><b>{step>i+1?'✓':i+1}</b>{s}</span>)}</div>
{step===1&&<><div className={`discovery ${selected.color}`}><div className="discovery-art"><img src={pic(selected)} alt={`${selected.word} terimini anlatan görsel`}/><span aria-hidden="true">{selected.emoji}</span></div><small>{selected.category}{selected.syllables&&selected.syllables!==selected.word&&` · ${selected.syllables}`}</small><h2>{selected.word}</h2><small>{emojiOf(selected.work)} {src(selected).title}</small></div><h3>Sence ne anlama geliyor?</h3><label className="sr-only" htmlFor="guess">Tanım tahminin</label><input id="guess" placeholder="Aklına ilk geleni yaz…" value={guess} maxLength={160} onChange={e=>setGuess(e.target.value)}/>{!revealed?<button className="primary wide" onClick={()=>setRevealed(true)}>{guess?'Tanımını keşfet':'Tahmin etmeden tanımını gör'} ↓</button>:<><div className="meaning"><span className="eyebrow">TERİMİN TANIMI</span><Meanings w={selected} k={src(selected)}/><Source w={selected} k={src(selected)}/></div><button className="primary wide" onClick={()=>setStep(2)}>Şimdi benim cümlem ↗</button></>}</>}
{step===2&&<><div className="eyebrow">SÖZ SIRASI SENDE</div><h2>“{selected.word}” terimini<br/>sen nasıl kullanırsın?</h2><p>{selected.oldMeaning||selected.meaning}</p><label>Kendi cümlen<textarea maxLength={240} rows={4} placeholder={`“${selected.word}” terimini kullanarak bir cümle yaz…`} value={sentence} onChange={e=>{setSentence(e.target.value);setFeedback(null);}}/><small>{sentence.length}/240 · Terimi cümlende kullan.</small></label>{teacher&&<div className="teacher"><button className="secondary" disabled={checking||sentence.trim().length<3} onClick={askTeacher}>{checking?'Yapay zekâ öğretmen okuyor…':'✦ Yapay zekâ öğretmen cümleme baksın'}</button>{feedback&&<p className={feedback.ok?'good':'tip'} role="status">{feedback.ok?'👏 ':'💡 '}{feedback.text}</p>}</div>}<details className="hint"><summary>✧ Biraz ilham ister misin?</summary><p>Örnek: “{selected.example}”</p><p>Bu terimi bir projende, yarışmada ya da günlük hayatında nerede kullanırsın?</p></details><label>Takma adın <small>(isteğe bağlı)</small><input maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="Örn. Kod Kâşifi"/><small>Gerçek adın yerine bir takma ad kullan.</small></label><div className="button-row"><button className="secondary" onClick={()=>setStep(1)}>← Geri</button><button className="primary" disabled={!sentenceValid} onClick={()=>setStep(3)}>Kartımı görselleştir ↗</button></div></>}
{step===3&&<><div className="eyebrow">TERİMİ GÖRSELLEŞTİR</div><h2>Bu terim nasıl bir sahne anlatır?</h2><blockquote className="own-sentence">“{sentence}”</blockquote><label>Görselinde neler olsun?<textarea maxLength={400} rows={3} value={scene} onChange={e=>setScene(e.target.value)} placeholder="Nerede geçiyor? Hangi araçlar, kişiler, ekranlar var?"/></label><button className="text-button" onClick={()=>setScene(selected.scene)}>✧ Bir sahne fikri kullan</button><fieldset><legend>Görselinin tarzı</legend><div className="style-grid">{styles.map((s,i)=><button type="button" key={s} className={style===s?'selected':''} onClick={()=>setStyle(s)}><span>{['❋','▦','✧'][i]}</span>{s}</button>)}</div></fieldset><div className="info-box">{ai?<label className="check"><input type="checkbox" checked={mode==='demo'} onChange={e=>setMode(e.target.checked?'demo':'ai')}/> Hazır görselle hızlı deneme yap</label>:<><b>Hazır görselle deneme</b><p>Canlı yapay zekâ şu anda bağlı değil. Kartında hazır bir görsel kullanılacak; tarifin ve tarz seçimin kaydedilecek.</p></>}</div><div className="button-row"><button className="secondary" disabled={busy} onClick={()=>setStep(2)}>← Geri</button><button className="primary" disabled={busy||scene.trim().length<5} onClick={create}>{busy?'Kartın hazırlanıyor…':mode==='ai'?'✦ Yapay zekâ ile oluştur':'Terim kartımı oluştur ↗'}</button></div>{busy&&<p role="status">Kartın hazırlanırken: Bu terimi çalışma grubunda başka nerede duydun?</p>}</>}
{step===4&&card&&<><div className="result-heading"><span className="eyebrow">KARTIN HAZIR</span><h2>Bir terimden, bir karta.</h2></div><article className="result-card" id="print-card"><div className="print-brand">GENÇTEK · TERİMLER SÖZLÜĞÜ</div><img src={card.image} alt={`${selected.word}: ${card.mode==='ai'?card.scene:'terime eşlik eden hazır görsel'}`}/><div><span className="eyebrow">{card.mode==='ai'?'YAPAY ZEKÂ GÖRSELİ':'HAZIR GÖRSEL İLE OLUŞTURULDU'}</span><h2>{selected.word}</h2><p>{selected.meaning}</p><small className="card-source">{emojiOf(selected.work)} {src(selected).title}</small><blockquote>“{card.sentence}”</blockquote><div className="result-meta"><span>✦ {card.nickname}</span><span>{new Date(card.createdAt).toLocaleDateString('tr-TR')}</span></div></div>{qr&&<div className="qr-row"><img src={qr} alt="Kart bağlantısının QR kodu"/><small>Kartını telefonunda açmak için okut.</small></div>}</article><div className="button-row result-actions"><button className="primary" onClick={download}>↓ Kartımı indir</button><button className="secondary" onClick={()=>window.print()}>Yazdır</button><button className="secondary" onClick={copy}>Bağlantıyı kopyala</button></div><p className="source-note">{card.approved===1?'Kartın ortak sözlükte yayımlandı.':card.approved===-1?'Bu kart ortak sözlükte yayımlanmadı.':'Kartın kaydedildi. Görevli onayından sonra ortak sözlükte görünecek.'}</p><button className="text-button wide" onClick={close}>Yeni bir terim keşfet ↗</button></>}
</>}
{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}
</div></dialog></>;
}
